create table if not exists public.respuestas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  tipo_registro text not null check (tipo_registro in ('unidad', 'respuesta', 'consultorio', 'horario')),
  entidad text,
  usuario_nombre text,
  usuario_email text,
  clues_imb text not null,
  nombre_de_la_unidad text,
  categoria_gerencial_ampliada text,
  internet text check (internet in ('SI', 'NO', 'PENDIENTE')),
  consultorios_habilitados integer check (consultorios_habilitados >= 0),
  consultorios_inhabilitados integer check (consultorios_inhabilitados >= 0),
  total_consultorios_medicina_general integer check (total_consultorios_medicina_general >= 0),
  consultorios integer check (consultorios between 0 and 20),
  consultorio integer,
  pregunta text,
  valor integer check (valor is null or valor >= 0),
  turno text,
  habilitado boolean,
  causas_inhabilitacion text not null default '',
  medicos_generales integer check (medicos_generales is null or medicos_generales >= 0),
  medico_disponible boolean,
  horarios jsonb not null default '{}'::jsonb check (jsonb_typeof(horarios) = 'object')
);

alter table public.respuestas
  add column if not exists consultorios_inhabilitados integer
    check (consultorios_inhabilitados >= 0),
  add column if not exists total_consultorios_medicina_general integer
    check (total_consultorios_medicina_general >= 0),
  add column if not exists consultorios integer
    check (consultorios between 0 and 20),
  add column if not exists habilitado boolean,
  add column if not exists causas_inhabilitacion text not null default '',
  add column if not exists medicos_generales integer
    check (medicos_generales is null or medicos_generales >= 0),
  add column if not exists medico_disponible boolean,
  add column if not exists horarios jsonb not null default '{}'::jsonb;

do $migration$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'respuestas'
      and column_name = 'causas_inhabilitacion'
      and udt_name = '_text'
  ) then
    execute $sql$
      alter table public.respuestas
        alter column causas_inhabilitacion drop default,
        alter column causas_inhabilitacion type text
          using array_to_string(causas_inhabilitacion, ', '),
        alter column causas_inhabilitacion set default ''
    $sql$;
  end if;
end;
$migration$;

alter table public.respuestas
  alter column horarios set default '{}'::jsonb,
  drop constraint if exists respuestas_horarios_check,
  add constraint respuestas_horarios_check
    check (jsonb_typeof(horarios) = 'object');

alter table public.respuestas
  drop constraint if exists respuestas_tipo_datos_check,
  drop constraint if exists respuestas_condicion_funcionamiento_check;

delete from public.respuestas
where tipo_registro = 'respuesta'
  and valor is null;

alter table public.respuestas
  drop column if exists condicion_funcionamiento;

alter table public.respuestas
  drop constraint if exists respuestas_turno_check;

alter table public.respuestas
  add constraint respuestas_turno_check check (
    turno is null or turno in (
      '',
      'Matutino',
      'Matutino lunes a viernes',
      'Matutino miércoles a domingo',
      'Matutino sábados y domingos (fin de semana)',
      'Vespertino',
      'Ambos'
    ) or turno ~ '^(Matutino|Vespertino) - .+$'
  );

alter table public.respuestas
  drop constraint if exists respuestas_tipo_registro_check,
  add constraint respuestas_tipo_registro_check
    check (tipo_registro in ('unidad', 'respuesta', 'consultorio', 'horario')),
  add constraint respuestas_tipo_datos_check check (
    (tipo_registro = 'unidad' and consultorio is null and pregunta is null and valor is null and turno is null)
    or
    (tipo_registro = 'respuesta' and consultorio > 0
        and pregunta is not null
        and pregunta <> 'consultorios'
      and pregunta <> '¿Cuántos médicos generales tiene?'
      and pregunta not like '¿Opera en este horario?%'
      and pregunta not like '¿Cuenta con médico general?%'
        and consultorios is null
        and internet is null
        and consultorios_habilitados is null
        and consultorios_inhabilitados is null
        and total_consultorios_medicina_general is null
        and valor is not null
        and turno is null)
    or
    (tipo_registro = 'consultorio' and consultorio > 0
      and pregunta is null and valor is null and internet is null
      and consultorios_habilitados is null
      and consultorios is null
      and consultorios_inhabilitados is null
      and total_consultorios_medicina_general is null)
    or
    (tipo_registro = 'horario' and consultorio > 0
      and pregunta is null and valor is null
      and turno ~ '^(Matutino|Vespertino) - .+$'
      and consultorios is null and internet is null
      and consultorios_habilitados is null
      and consultorios_inhabilitados is null
      and total_consultorios_medicina_general is null
      and medicos_generales is null)
  );

create unique index if not exists respuestas_unidad_clues_uidx
  on public.respuestas (clues_imb)
  where tipo_registro = 'unidad';

create unique index if not exists respuestas_celda_uidx
  on public.respuestas (clues_imb, consultorio, pregunta)
  where tipo_registro = 'respuesta';

create unique index if not exists respuestas_consultorio_uidx
  on public.respuestas (clues_imb, consultorio)
  where tipo_registro = 'consultorio';

create unique index if not exists respuestas_horario_uidx
  on public.respuestas (clues_imb, consultorio, turno)
  where tipo_registro = 'horario';

create index if not exists respuestas_clues_idx on public.respuestas (clues_imb);

comment on column public.respuestas.consultorio is
  'Número de consultorio para filas de configuración y equipamiento.';

comment on column public.respuestas.pregunta is
  'Pregunta de equipamiento; es nula en filas de unidad y consultorio.';

comment on column public.respuestas.turno is
  'Turno operativo del consultorio o combinación turno - día en filas de horario.';

comment on column public.respuestas.medicos_generales is
  'Número de médicos generales; solo se usa en la fila del consultorio.';

create or replace function public.proteger_borrado_respuestas()
returns trigger
language plpgsql
as $$
begin
  if current_setting('app.permitir_borrado_respuestas', true) is distinct from 'on' then
    raise exception 'Borrado bloqueado: use la función autorizada para eliminar respuestas.';
  end if;
  return null;
end;
$$;

drop trigger if exists respuestas_bloquear_delete on public.respuestas;
create trigger respuestas_bloquear_delete
before delete on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

drop trigger if exists respuestas_bloquear_truncate on public.respuestas;
create trigger respuestas_bloquear_truncate
before truncate on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

create or replace function public.eliminar_respuestas_unidad(p_clues text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_eliminadas integer;
begin
  if nullif(trim(p_clues), '') is null then
    raise exception 'CLUES es obligatoria';
  end if;

  perform set_config('app.permitir_borrado_respuestas', 'on', true);

  delete from public.respuestas
  where clues_imb = upper(trim(p_clues))
    and tipo_registro in ('respuesta', 'consultorio', 'horario');

  get diagnostics filas_eliminadas = row_count;

  return filas_eliminadas;
end;
$$;

revoke all on function public.eliminar_respuestas_unidad(text) from public, authenticated;
grant execute on function public.eliminar_respuestas_unidad(text) to anon, service_role;

create or replace function public.eliminar_horarios_turno(
  p_clues text,
  p_consultorio integer,
  p_turno text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_eliminadas integer;
begin
  if nullif(trim(p_clues), '') is null
    or p_consultorio <= 0
    or p_turno not in ('Matutino', 'Vespertino') then
    raise exception 'Parámetros de turno inválidos';
  end if;

  perform set_config('app.permitir_borrado_respuestas', 'on', true);

  delete from public.respuestas
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'horario'
    and consultorio = p_consultorio
    and turno like p_turno || ' - %';

  get diagnostics filas_eliminadas = row_count;
  return filas_eliminadas;
end;
$$;

revoke all on function public.eliminar_horarios_turno(text, integer, text) from public, authenticated;
grant execute on function public.eliminar_horarios_turno(text, integer, text) to anon, service_role;

alter table public.respuestas enable row level security;

grant select, insert, update on table public.respuestas to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists respuestas_anon_select on public.respuestas;
create policy respuestas_anon_select
  on public.respuestas for select
  to anon
  using (true);

drop policy if exists respuestas_anon_insert on public.respuestas;
create policy respuestas_anon_insert
  on public.respuestas for insert
  to anon
  with check (true);

drop policy if exists respuestas_anon_update on public.respuestas;
create policy respuestas_anon_update
  on public.respuestas for update
  to anon
  using (true)
  with check (true);
