create table if not exists public.respuestas (
  id bigint generated by default as identity primary key,
  fecha_registro timestamptz not null default now(),
  tipo_registro text not null check (tipo_registro in ('unidad', 'respuesta')),
  entidad text,
  usuario_nombre text,
  usuario_email text,
  clues_imb text not null,
  nombre_de_la_unidad text,
  categoria_gerencial_ampliada text,
  internet text check (internet in ('SI', 'NO', 'PENDIENTE')),
  consultorios_habilitados integer check (consultorios_habilitados >= 0),
  consultorio integer,
  pregunta text,
  valor integer check (valor is null or valor >= 0),
  turno text
);

alter table public.respuestas
  drop constraint if exists respuestas_tipo_datos_check;

update public.respuestas
set consultorio = valor,
    valor = null
where tipo_registro = 'respuesta'
  and pregunta = 'consultorios'
  and valor is not null;

alter table public.respuestas
  drop column if exists consultorios;

alter table public.respuestas
  add constraint respuestas_tipo_datos_check check (
    (tipo_registro = 'unidad' and consultorio is null and pregunta is null and valor is null and turno is null)
    or
    (tipo_registro = 'respuesta' and consultorio is not null
      and ((pregunta = 'consultorios' and consultorio between 0 and 20) or (pregunta <> 'consultorios' and consultorio > 0))
      and pregunta is not null and internet is null and consultorios_habilitados is null)
  );

create unique index if not exists respuestas_unidad_clues_uidx
  on public.respuestas (clues_imb)
  where tipo_registro = 'unidad';

create unique index if not exists respuestas_celda_uidx
  on public.respuestas (clues_imb, consultorio, pregunta)
  where tipo_registro = 'respuesta';

create index if not exists respuestas_clues_idx on public.respuestas (clues_imb);

create or replace function public.proteger_borrado_respuestas()
returns trigger
language plpgsql
as $$
begin
  if current_setting('app.permitir_borrado_respuestas', true) is distinct from 'on' then
    raise exception 'Borrado bloqueado: use la función autorizada para eliminar respuestas.';
  end if;
  return null;
end;
$$;

drop trigger if exists respuestas_bloquear_delete on public.respuestas;
create trigger respuestas_bloquear_delete
before delete on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

drop trigger if exists respuestas_bloquear_truncate on public.respuestas;
create trigger respuestas_bloquear_truncate
before truncate on public.respuestas
for each statement
execute function public.proteger_borrado_respuestas();

create or replace function public.eliminar_respuestas_unidad(p_clues text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  filas_eliminadas integer;
begin
  perform set_config('app.permitir_borrado_respuestas', 'on', true);

  delete from public.respuestas
  where clues_imb = upper(trim(p_clues))
    and tipo_registro = 'respuesta'
    and pregunta <> 'consultorios';

  get diagnostics filas_eliminadas = row_count;
  return filas_eliminadas;
end;
$$;

revoke all on function public.eliminar_respuestas_unidad(text) from public, anon, authenticated;
grant execute on function public.eliminar_respuestas_unidad(text) to service_role;

alter table public.respuestas disable row level security;